### ISSUE TITLE
Compilation error on ESP32 #8 (now on arduino) 

### ISSUE THREAD

**Issue by wesssup** [MajicDesigns/MD_YX5300#11]
Same as #8 error .... but now on Arduino IDE

**Comment by MajicDesigns** [comment]
Fixed for one is fixed for all. Are you running the latest version?  Check if the changes from previous fix are in your library.

**Comment by wesssup** [comment]
Error "C:\Users\XXXX\Documents\Arduino\libraries\MD_YX5300\src/MD_YX5300.h:12:28: fatal error: SoftwareSerial.h: No such file or directory"


![image](https://user-images.githubusercontent.com/22135530/92231208-aba93480-eeac-11ea-8f86-1c356c109381.png)
Using arduino Libs management , version is 1.2.4 on a fresh Arduino (1.8.13) / PC installation  / Heltec wirelessstick board 
 
![image](https://user-images.githubusercontent.com/22135530/92234740-ddbd9500-eeb2-11ea-9483-59b59a24026b.png)

![image](https://user-images.githubusercontent.com/22135530/92234805-fb8afa00-eeb2-11ea-8e3f-23f1012ba399.png)

**Comment by MajicDesigns** [comment]
Just tried it on my setup (Windows 10, IDE 1.8.13, Uno) and no errors reported with verbose output turned on.

**Comment by wesssup** [comment]
Hi,

Same test here :-) with 'MD_YX5300_Test' and Uno board ... working as expected. 
Compiling code with the **Heltec wireless stick board,** compilation failed (ESP32 dual-core 32-bit MCU + ULP core).
_(Can be tested by downloading the Heltec Wireless Stick board in the BoardManager and try to compile it)_ 

We did some more tests on our stock of arduino/ESP32 variants, like NodeMcu (different versions) and Sonoff types, all are working as expected.  But somehow for the Heltec Wirelesstick we bumped into the _"fatal error: SoftwareSerial.h: No such file or directory"_

Basically for this module(and according Google also some other)  "SoftwareSerial" is not supported and "HardwareSerial" should be used as there's direct hardware support.  It seams even the vendor did not deliver support into it's board package. *sigh* 
Anyway 'Serial' option in the "MD_YX5300" lib was also not selected automatically, manual switch showed us some issues.... 

We are working on a time-critical project and decided to implement a workaround by using HardwareSerial and send directly the commands over the serial connection to the connected _HW-311 MP3 player board._

>Code Below< . Could help someone else bumping into the same issue with the Heltec Boards :-) or adding Heltec support to the very nice MD_YX5300 lib !!! (we will use it for other boards for sure) 

Many Thanks 

Wesley 

```
//Raw testing code 

#include <HardwareSerial.h>

/************Command byte**************************/
#define CMD_NEXT_SONG 0X01
#define CMD_PREV_SONG 0X02
#define CMD_PLAY_W_INDEX 0X03
#define CMD_VOLUME_UP 0X04
#define CMD_VOLUME_DOWN 0X05
#define CMD_SET_VOLUME 0X06
#define CMD_SINGLE_CYCLE_PLAY 0X08
#define CMD_SEL_DEV 0X09
#define DEV_TF 0X02
#define CMD_SLEEP_MODE 0X0A
#define CMD_WAKE_UP 0X0B
#define CMD_RESET 0X0C
#define CMD_PLAY 0X0D
#define CMD_PAUSE 0X0E
#define CMD_PLAY_FOLDER_FILE 0X0F
#define CMD_STOP_PLAY 0X16
#define CMD_FOLDER_CYCLE 0X17
#define CMD_SET_SINGLE_CYCLE 0X19
#define SINGLE_CYCLE_ON 0X00
#define SINGLE_CYCLE_OFF 0X01
#define CMD_SET_DAC 0X1A
#define DAC_ON  0X00
#define DAC_OFF 0X01
#define CMD_PLAY_W_VOL 0X22

HardwareSerial Serial6(2);

/*
 * HW Serial Steering Audio ObjectsConnected Module  
 * @command See Module Command List
 * @dat     Parameter Command
 */
void sendCommand(int8_t command, int16_t dat){
  delay(20); 
  Send_buf[0] = 0x7e;
  Send_buf[1] = 0xff;
  Send_buf[2] = 0x06;
  Send_buf[3] = command;
  Send_buf[4] = 0x00;
  Send_buf[5] = (int8_t)(dat >> 8);//datah
  Send_buf[6] = (int8_t)(dat); //datal
  Send_buf[7] = 0xef; //
  for(uint8_t i=0; i<8; i++)//  {
    Serial6.write(Send_buf[i]);  
  }

setup(
  // Serial2.begin(unsigned long baud, uint32_t config, int8_t rxPin, int8_t txPin, bool invert)
  // The txPin & rxPin can set to any output pin
  Serial6.begin(9600, SERIAL_8N1, 33, 32);

)

loop(
   //example code 
   sendCommand(CMD_PLAY_W_INDEX,2);
)

```

**Comment by MajicDesigns** [comment]
v1.3 just released may be better for you as you control the Stream object from the application.
