### ISSUE TITLE
How to list the files on the SD card?

### ISSUE THREAD

**Issue by toncho11** [MajicDesigns/MD_YX5300#12]
Hi,

Is it possible to get the names of songs ?
Is it with STS_FLDR_FILES ?

**Comment by MajicDesigns** [comment]
There is no way to get the names of the files on the SD card. STS_FLDR_FILES returns the number of files in a folder.

Please also refer to the library documentation at file:///C:/Users/Marco/Documents/Programming/Arduino/Sketchbook/libraries/MD_YX5300/docs/index.html or in your docs folder for the library.
