### ISSUE TITLE
XC3748 JayCar Module Support

### ISSUE THREAD

**Issue by timo-quinn** [MajicDesigns/MD_YX5300#13]
I've purchased some Duinotech XC3748 modules from Jaycar, and am attempting to modify them to play in shuffle mode. However deployment of _any_ code via Sketch is failing through a USB to Serial converter. I get a flashing Rx light occasionally but nothing more than that, but I can see messages in a serial monitor when the device starts playing files.

Is this a device you have tested before by any chance? The reason I've come to this repo is that the Jaycar docs specifically references this library in their manual: https://www.jaycar.com.au/mp3-audio-player-module-with-6-push-button-switches-for-arduino/p/XC3748

I'm also very new to arduino dev so bear with me if I'm doing something blatantly stupid.

## Your Environment
**Library Version:** 1.3.1
**OS and Version:** Windows 10
````

**Comment by MajicDesigns** [comment]
It's news to me that they are referencing my library! I have never tested this device with the library but I can only assume that they have or they would not be pointing you there (reasonable assumption as this is the first enquiry I have had about this device).

The code is downloaded to an Arduino microprocessor, not this board. The processor then communicates to the device via serial to make it do stuff. Are you trying to program/download to the device directly?

**Comment by timo-quinn** [comment]
Yeah that's what they didn't make clear, that the serial connection is just another means to control it, not reprogram it - I finally got it working with an arduino in between :D

**Comment by CowboyJesus69** [comment]
Hello, how did the project you made with this module turn out? I have that module too and I'm wondering what the S-out on it means. i assume its Serial out, but what does it do? 
Thanks.

**Comment by MajicDesigns** [comment]
The serial protocol between the processor and XC3748 uses a request/response so the module needs to both receive and send data.

**Comment by cl-tim** [comment]
> Hello, how did the project you made with this module turn out? I have that module too and I'm wondering what the S-out on it means. i assume its Serial out, but what does it do? 
> Thanks.

I connected it to an Arduino, installing the MD_YX5300 library.

This is how I set up the script for the arduino:

```
// NOTE: this does not work at all: mp3.playFolderShuffle(PLAY_FOLDER);

#include <MD_YX5300.h>
#include <SoftwareSerial.h>
#include <Logger.h>

const uint8_t ARDUINO_RX = 2;    // connect to TX of MP3 Player module
const uint8_t ARDUINO_TX = 3;    // connect to RX of MP3 Player module

SoftwareSerial  MP3Stream(ARDUINO_RX, ARDUINO_TX);  // MP3 player serial stream for comms

MD_YX5300 mp3(MP3Stream);
```

**Comment by CowboyJesus69** [comment]
Do you know if using an Arduino with a screen on it could read the serial output and display things?

**Comment by cl-tim** [comment]
> Do you know if using an Arduino with a screen on it could read the serial output and display things?
> 
> 
> 

Potentially. But the only thing I did with the device was play audio files randomly from an SD card on a schedule, that's all. I didn't play around any further once I got that working.

**Comment by CowboyJesus69** [comment]
Does anyone have the datasheet for this or know what the G and V beside the UART and what the S-Out is?

**Comment by MajicDesigns** [comment]
Surely G and V would be Ground and Voltage (Vcc)?

**Comment by CowboyJesus69** [comment]
Thats what I thought too but I can't find any documentation

**Comment by MajicDesigns** [comment]
So what is the question? You can easily trace the circuit to see if the connections support the G/V interpretation. If something is not working, take it back to the store and get them to explain it to you.

**Comment by JedBoom** [comment]
Hello, I am using this module and needing to trigger a file to play with a pir sensor input via an arduino Uno. Here's the code but im not getting any sound to play.


```cpp
#include <SoftwareSerial.h>
#include <stdlib.h>

// define the pins for the PIR sensor and the XC3748 module
const int PIR_PIN = 2;    // PIR sensor connected to pin 2
const int XC3748_TX = 1;  // XC3748 module's RX pin connected to Arduino's TX pin
const int XC3748_RX = 0;  // XC3748 module's TX pin connected to Arduino's RX pin

// create a SoftwareSerial object for the XC3748 module
SoftwareSerial mp3(XC3748_RX, XC3748_TX);

void setup() {
  // initialize the serial communication for debugging
  Serial.begin(9600);
  
  // initialize the PIR sensor pin as input
  pinMode(PIR_PIN, INPUT);
  
  // initialize the SoftwareSerial object for the XC3748 module
  mp3.begin(9600);
  
  // wait for the XC3748 module to initialize
  delay(500);
  
  // set the volume of the XC3748 module to maximum
  mp3.write(0x7E);  // start code
  mp3.write(0x03);  // length
  mp3.write(0xA7);  // command
  mp3.write(0x7F);  // parameter
  mp3.write(0xEF);  // end code
}

void loop() {
  // read the PIR sensor input
  int pirValue = digitalRead(PIR_PIN);
  
  // if motion is detected, play a random track on the XC3748 module
  if (pirValue == HIGH) {
    Serial.println("Motion detected!");
    int trackNum = random(1, 10);  // generate a random track number between 1 and 9
    String trackName = String(trackNum, 3) + "trk.mp3";  // format the track name string
    Serial.println("Playing track " + trackName);
    mp3.write(0x7E);  // start code
    mp3.write(0x06);  // length
    mp3.write(0xA0);  // command
    mp3.write(0x01);  // parameter 1 (play mode: repeat)
    mp3.write(random(1, 10));
    mp3.write(0xEF);  // end code
    
  }
  
  // wait for a short time before checking the PIR sensor again
  delay(100);
}

```

**Comment by MajicDesigns** [comment]
Sorry but this is not a general help desk for this hardware or your code. As you are not using my library the question may be better directed at generic help forums (like arduino.cc).
