### ISSUE TITLE
MD_YX5300::STS_FILE_END called twice

### ISSUE THREAD

**Issue by thijstriemstra** [MajicDesigns/MD_YX5300#14]
Starting playback of a file, and when it's finished `MD_YX5300::STS_FILE_END` callback is called twice

## Your Environment
**Library Version:** 1.3.1
**Arduino IDE version:** Using platformio
**Hardware model/type:** Wemos D1 Lite (esp8266)
**OS and Version:** Ubuntu 20 LTS

```cfg
[env:xy5300_test]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 74880
upload_speed = 115200

lib_deps =
  majicdesigns/MD_YX5300

build_flags =
  ; -----------------------------
  ; YX5300 audio player
  ; -----------------------------
  -D AudioRXPin=13
  -D AudioTXPin=12
  -D AudioVolume=20
```

## Steps to Reproduce
```c++
_stream = new SoftwareSerial(rx_pin, tx_pin);
_player = new MD_YX5300(*_stream);
_stream->begin(MD_YX5300::SERIAL_BPS);
_player->begin();
_player->setSynchronous(false);
_player->setCallback(cbResponse);
_player->queryFilesCount();
_player->queryVolume();
_player->playNext();
```

## Expected Behaviour
I expect `MD_YX5300::STS_FILE_END` to be called once.

**Comment by MajicDesigns** [comment]
The callback is triggered by receiving the message from the MP3 player. Have you checked that you are not getting the STS_FILE_END message twice from the device? You can turn on debug in the library to see the actual data being send to and from the device in the serial monitor.

**Comment by thijstriemstra** [comment]
Here is the debug output (with some log statements of my own):

```
MD_YX5300 - Loaded folders.
MD_YX5300 - Playing random track 75 from folder 1

0081703 S:  7E FF 06 0F 01 01 4B FE 9F EF
0081724 R:  7E FF 06 41 00 00 12 FE A8 EF -> 41 : Ack OK
0081727 R:  7E FF 06 41 00 00 00 FE BA EF -> 41 : Ack OK
0081762 R:  7E FF 06 41 00 00 00 FE BA EF -> 41 : Ack OK
0358263 R:  7E FF 06 3D 00 00 4B FE 73 EF -> 3D : Ended track 75
MD_YX5300 - File ended.

0358275 R:  7E FF 06 3D 00 00 4B FE 73 EF -> 3D : Ended track 75
MD_YX5300 - File ended.
```

Note I'm using `playSpecific` in this log but it happens with `playNext` as well.

**Comment by thijstriemstra** [comment]
Another issue I see, maybe related, maybe not is using calling `queryFolderFiles` multiple times for multiple folders. Output:

```
MD_YX5300 - Total folders:      6

0079753 S:  7E FF 06 4E 01 00 01 FE AB EF
0079847 R:  7E FF 06 4E 00 00 BB FD F2 EF -> 4E : Folder files 187
MD_YX5300 - Total for folder 1: 187

0079878 S:  7E FF 06 4E 01 00 02 FE AA EF
0079899 R:  7E FF 06 41 00 00 BB FD FF EF -> 41 : Ack OK
0080074 R:  7E FF 06 4E 00 00 39 FE 74 EF -> 4E : Folder files 57
MD_YX5300 - Total for folder 2: 57

0080105 S:  7E FF 06 4E 01 00 03 FE A9 EF
0080126 R:  7E FF 06 41 00 00 39 FE 81 EF -> 41 : Ack OK
0080339 R:  7E FF 06 4E 00 00 13 FE 9A EF -> 4E : Folder files 19
MD_YX5300 - Total for folder 3: 19

0080369 S:  7E FF 06 4E 01 00 04 FE A8 EF
0080390 R:  7E FF 06 41 00 00 13 FE A7 EF -> 41 : Ack OK
0080613 R:  7E FF 06 4E 00 00 12 FE 9B EF -> 4E : Folder files 18
MD_YX5300 - Total for folder 4: 18

0080644 S:  7E FF 06 4E 01 00 05 FE A7 EF
0080665 R:  7E FF 06 41 00 00 12 FE A8 EF -> 41 : Ack OK
0080913 R:  7E EF -> 2 : Ver error
MD_YX5300 - STS_VERSION

0080923 R:  7E FF 06 41 00 00 2F FE 8B EF -> 41 : Ack OK
```

For some reason I can't invoke that call for the 5th and 6th folder on that disk. Odd thing is that it throws a `STS_VERSION`? Maybe related, something with my device?

**Comment by MajicDesigns** [comment]
0358263 R:  7E FF 06 3D 00 00 4B FE 73 EF -> 3D : Ended track 75
MD_YX5300 - File ended.

0358275 R:  7E FF 06 3D 00 00 4B FE 73 EF -> 3D : Ended track 75
MD_YX5300 - File ended.

Tells me that you are processing an end of track message twice, 12 milliseconds apart. This could be the device sending it twice or your code somehow processing the same message twice (synchoronous and callback, maybe?). Do you get the same effect with the example CLI test code playing the same track (with library debug turned on)?

With respect to queryFolderFiles, is this related to the folders or to the number of calls to the function? For example, if you try and do the folders in reverse order, does the failure still happen and, if so, at the same folders or at the same number of functions calls?

**Comment by thijstriemstra** [comment]
> Do you get the same effect with the example CLI test code playing the same track (with library debug turned on)?

Good question, I'll try.

> With respect to queryFolderFiles, is this related to the folders or to the number of calls to the function? 

Flow of my query folder code is: `queryFolderFiles(1)` -> in callback save result and wait 20ms -> `queryFolderFiles(2)` -> in callback save result and wait 20ms -> etc

This works for 4 directories. I'm 99% certain it's not my code sending it out twice. Note that I need to add a small delay of 20ms or higher between the calls, otherwise the first call doesn't get a response at all (or times out almost immediately).  

> For example, if you try and do the folders in reverse order, does the failure still happen and, if so, at the same folders or at the same number of functions calls?

I'll give that a try.

**Comment by thijstriemstra** [comment]
I should probably note that I'm not using a Catalex branded MP3 player but rather a so called [HW-311 YX5300 MP3 player module](https://arduino.en.alibaba.com/product/62335601537-813789664/HW_311_YX5300_MP3_player_module_Voice_serial_control_music_audio_module_with_TF_card_slot.html), but not sure if that matters.. (hope not!)

![H0f03d63b42ce4468b88945d55712e080e](https://user-images.githubusercontent.com/305679/117457729-ceaf4b00-af49-11eb-9c2e-96bf6c615cce.jpg)

**Comment by thijstriemstra** [comment]
Also found this in the chinese datasheet:

```
5. If you specify the folder file name to play [0x0F command], the delay must
be greater than 40ms, because it takes time for the chip to lock the file.
As long as it involves the relevant instructions for searching the folder file name,
the delay of 40MS is indispensable. If the chip is currently looking for files
If the serial port data comes in too frequently, it will cause the chip to reset
 ```

This sounds very familiar.. Does your code take that 40ms into consideration @MajicDesigns?

I also noticed the first file in folder 5 contains a long filename `281-Chevaliers De Sangreal (From The Da Vinci Code Original Motion Picture Soundtrack).mp3` but I couldn't find anything in the datasheet about any filename length limitations. Changing the name to something shorter didn't make a difference.

In that same folder 5 I also saw some filenames contain `.` and `'`, e.g. `313-F.A.B.mp3` and `285-L'Esprit Des Gabriel.mp3`. Changing this also didn't seem to help.

Both folder 4 and 5 contained a track that started with `281-`. Unfortunately this didn't fix the issue either.

What finally 'fixed' it was getting rid of the content in folder 5. I then copied some random directories and tested up till 9 folders, all worked fine. So it seems there is an issue somewhere with folder 5, containing this list of files (320kbs):

```
001-Chevaliers De Sangreal (From The Da Vinci Code Original Motion Picture Soundtrack).mp3
002-Gun Barrel (From No Time To Die Soundtrack).mp3
003-The Battle (From _Gladiator_ Soundtrack).mp3
004-Main Theme [Rain Man] (Edit).mp3
005-L'Esprit Des Gabriel.mp3
006-Now We Are Free (From _Gladiator_ Soundtrack).mp3
007-Progeny (From _Gladiator_ Soundtrack).mp3
008-Tracy Island.mp3
009-Honor Him (From _Gladiator_ Soundtrack).mp3
010-All That Remains (From _Gladiator_ Soundtrack).mp3
011-Time (arr. guitar) (From _Inception_).mp3
012-Maximus (From _Gladiator_ Soundtrack).mp3
013-Leave No Man Behind.mp3
014-Still Reprise (From _Black Hawk Down_ Soundtrack).mp3
015-Before You Die You See The Ring.mp3
016-To Zuccabar (From _Gladiator_ Soundtrack).mp3
017-The General Who Became A Slave (From _Gladiator_ Soundtrack).mp3
018-Vale Of Plenty.mp3
019-Beneath Alrischa.mp3
020-Homecoming (From _Gladiator_ Soundtrack).mp3
021-Mogadishu Blues.mp3
022-Television.mp3
023-Burning Tree.mp3
024-Secrets (From _Gladiator_ Soundtrack).mp3
025-Earth (From _Gladiator_ Soundtrack).mp3
026-I'll Follow Your Voice.mp3
027-Ad Arcana.mp3
028-Malleus Maleficarum.mp3
029-Strength And Honor (From _Gladiator_ Soundtrack).mp3
030-Shelter Mountain.mp3
031-Reunion (From _Gladiator_ Soundtrack).mp3
032-Slaves To Rome (From _Gladiator_ Soundtrack).mp3
033-F.A.B.mp3
034-Fafafa...No Way!.mp3
035-Junior Mission.mp3
036-Dies Mercurii I Martius (From The Da Vinci Code Original Motion Picture Soundtrack).mp3
037-Poisoned Chalice.mp3
038-The Citrine Cross.mp3
039-Rose Of Arimathea.mp3
040-Hunger.mp3
041-This Is Going To Hurt.mp3
042-The Well.mp3
043-Patricide (From _Gladiator_ Soundtrack).mp3
044-Not Yet (From _Gladiator_ Soundtrack).mp3
045-Now We Are Free (Juba's Mix _ From _Gladiator_ Soundtrack).mp3
046-The Paschal Spiral.mp3
047-Fructus Gravis.mp3
```

**Comment by thijstriemstra** [comment]
Disabling the checksum results in a unresponsive device (although the docs mention it's optional):

```c++
#define USE_CHECKSUM       0
```

Tested with async mode.

**Comment by thijstriemstra** [comment]
Also noticed that the index passed to `STS_FILE_END` callback is incorrect..

```
MD_YX5300 - Playing random track 29 from folder 1
MD_YX5300 - File 48 ended at 478459
MD_YX5300 - File 48 ended at 478469
```

I'd expect it to say `File 29 ended at 478469`.

**Comment by MajicDesigns** [comment]
You should check the return message to see if it is actually telling you that file '29' ended. The return code is just this line of code:
`_status.data = ((uint16_t)_bufRx[5] << 8) | _bufRx[6];`
So you are looking at bytes 5 and 6 of the message buffer (first element is 0).

**Comment by thijstriemstra** [comment]
> You should check the return message

You mean like this?

```c++
void cbResponse(const MD_YX5300::cbData *status) {
  uint16_t data = status->data;

  switch (status->code) {
    case MD_YX5300::STS_FILE_END:
      Serial.println(data);
      break;
```

That's what returned the incorrect index..

> So you are looking at bytes 5 and 6 of the message buffer (first element is 0).

Not sure how to do this, I thought the library provided the correct index?

**Comment by thijstriemstra** [comment]
I also missed this in the documentation and eventually found it in the `YX5300-24SS` datasheet:

> 2. If the system is 5V. Then it is recommended to connect a 1K resistor in series
> with the docking interface of the serial port. This is enough to meet the general requirements,

![Screenshot from 2021-05-10 23-04-07](https://user-images.githubusercontent.com/305679/117724445-0b966e80-b1e4-11eb-8059-da090973bc2e.png)

Seems important.. so I'll give it a try.

**Comment by MajicDesigns** [comment]
> You should check the return message

means check the data that is coming back from the device (use debug in the library to see the bytes). The library does not do much other than pass back the code received. If it is reporting the data received then that is the best it can do.

The resistor is a kludge. It would be normal practice to use a voltage divider (or a level converter) to interface between the 5V and 3V system for signals going from the 5V system to the 3V system. This is described in may places, especially if you look for HC-05 bluetooth module interfacing.

Personally, the more I see of this YX5300 in action the less I like it. There are far too many things that are not how they should be.

**Comment by thijstriemstra** [comment]
> Personally, the more I see of this YX5300 in action the less I like it. There are far too many things that are not how they should be.

Agreed. Latest weirdness (besides everything else for my use-case working fine) is a wemos d1 mini crash when I plug something in the headphone jack, whether it's a headphone cable or jack cable to external amp, as soon as it's plugged the YX5300 because unresponsive and takes down the whole system with it.

I'm reluctantly ordering a new one and hoping that will solve the issue. I'll make sure it has the catalex branding on it:

![s-l1600](https://user-images.githubusercontent.com/305679/117882865-0ea86200-b2ab-11eb-9d90-92b8c8575399.jpg)

**Comment by thijstriemstra** [comment]
> I'm reluctantly ordering a new one and hoping that will solve the issue. 

I ordered a new one but received a XY6300,  see #16

I'll close this and consider it a hardware issue.

**Comment by thijstriemstra** [comment]
> I ordered a new one but received a XY6300, see #16
> I'll close this and consider it a hardware issue.

Unfortunately that new device has the same issue: file end is called twice.

```
MD_YX5300 - Playing random track 3 from folder 1
MD_YX5300 - File 4 ended at 170323
MD_YX5300 - Playing random track 2 from folder 1
MD_YX5300 - File 4 ended at 170354
MD_YX5300 - Playing random track 4 from folder 1
MD_YX5300 - File 5 ended at 349136
MD_YX5300 - Playing random track 1 from folder 1
MD_YX5300 - File 5 ended at 349167
MD_YX5300 - Playing random track 5 from folder 1
MD_YX5300 - File 6 ended at 446656
MD_YX5300 - Playing random track 3 from folder 1
MD_YX5300 - File 6 ended at 446687
MD_YX5300 - Playing random track 4 from folder 1
```

The nrs you see in the output are `millis()`. So File 6's `STS_FILE_END` event is called at 446656 and then again at 446687.
