### ISSUE TITLE
YX6300 chip supported?

### ISSUE THREAD

**Issue by thijstriemstra** [MajicDesigns/MD_YX5300#16]
I ordered a "Serial MP3 Player v1.0 YX5300" on ebay but received a "Serial MP3 Player v1.1" and there's a YX6300-24S chip on it.

Is this chip/board also compatible with this library?

There seems to be a v1.1 version of the manual/datasheet as well, attaching it here:

[serial_mp3_player_a_v1_1_manual_2iRjBvQd4w.pdf](https://github.com/MajicDesigns/MD_YX5300/files/6541537/serial_mp3_player_a_v1_1_manual_2iRjBvQd4w.pdf)

**Comment by thijstriemstra** [comment]
Looking at other suppliers, e.g. https://www.tinytronics.nl/shop/en/audio/mini-mp3-module-yx5300-with-audio-jack mentions:

> Moreover, the module may come with a compatible "JL" chip or YX6300 chip instead of the standard YX5300 chip.

So I'm going to guess it should be compatible. I'd like to know if there are any differences though, I hope YX6300 comes with some improvements?

**Comment by thijstriemstra** [comment]
couldn't find any images of the module online so posting a few made with camera:

 ![image](https://user-images.githubusercontent.com/305679/119548927-01a16d80-bd97-11eb-85b7-0cc13848fc0d.jpeg)

![image](https://user-images.githubusercontent.com/305679/119549145-3a414700-bd97-11eb-88da-973d8b9f1c41.jpeg)

**Comment by MajicDesigns** [comment]
The protocol format looks the same. the number of messages seems to be reduced, so there may be commands that won't work. However, many of the commands were not documented in the English documentation before, so who knows...

Try it and see.

**Comment by thijstriemstra** [comment]
Tested the board with a brand new D1 mini and the YX6300 chip looks like it works fine with this library, although I see an unknown status `0x90` at startup:

```
MD_YX5300 - STS_??? 0x90
MD_YX5300 - Total folders: 2
MD_YX5300 - Folder 1: 5 tracks
MD_YX5300 - Folder 2: 2 tracks
MD_YX5300 - Loaded 2 folders.
YX5300_AudioPlayer ready!!
```
