### ISSUE TITLE
Shuffle a folder?

### ISSUE THREAD

**Issue by chinswain** [MajicDesigns/MD_YX5300#2]
I noticed you mention folder shuffle does not work:

Known Issues
------------
- equalizer() command is accepted but not actioned by device. Documentation seems to indicate that
this function may be disabled in the hardware (Chinese translation is ambiguous).
**- playFolderShuffle() command is accepted but not actioned by the device.**
- shuffle() command is accepted but not seem to shuffle files playback.

If I send: "0X7e 0Xff 0X06 0X28 0X01 0X00 0X02 0Xef" it will shuffle folder 2 with no issues.

![random](https://user-images.githubusercontent.com/4403897/49691720-6e313f00-fb40-11e8-8eb7-38c3a88f8407.PNG)

**Comment by MajicDesigns** [comment]
Is this an issue? You have simply stated a fact.
