### ISSUE TITLE
Incorrect Callback responses after #define LIBDEBUG 0 in synchronous mode

### ISSUE THREAD

**Issue by ldalep** [MajicDesigns/MD_YX5300#3]
Using Setup:
void setup()
{
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(DET, INPUT);
  pinMode(PIN13, OUTPUT);

  Serial.begin(57600);
  Serial.print(F("\ninitializing...\n"));
  // 
  
  mp3.begin(); 
  
  setCallbackMode(true);
  setSynchMode(true);
  
  ParseMotor ("C1"); //CW
  ParseMotor ("C0"); //CCW
  delay(125); Stop (); // Just to put I/O low
   
    mp3.volume(25); 
    mp3.queryVolume(); 
    mp3.queryStatus(); 

   Serial.print(F("\nStarting..."));
}
I get a response with the debugger on  (WHICH IS CORRECT)->

initializing...

S:  7E FF 06 0C 01 00 00 FE EE EF
R:  -> 1 : Timeout
Synch wait over
S:  7E FF 06 09 01 00 02 FE EF EF
R:  7E FF 06 41 00 00 00 FE BA EF -> 41 : Ack OK
Synch wait over
>Callback ON
>Synchronous ON
CW Speed Cal= 1928
CCW Speed Cal= 300
S:  7E FF 06 06 01 00 19 FE DB EF
R:  7E FF 06 3F 00 00 02 FE BA EF -> 3F : Init 0x2
Cback status: STS_INIT, 0x2
Synch wait over
S:  7E FF 06 43 01 00 00 FE B7 EF
R:  7E FF 06 41 00 00 00 FE BA EF -> 41 : Ack OK
Cback status: STS_ACK_OK, 0x0
Synch wait over
S:  7E FF 06 42 01 00 00 FE B8 EF
R:  7E FF 06 43 00 00 19 FE 9F EF -> 43 : Vol 25
Cback status: STS_VOLUME, 0x19
Synch wait over
Starting...
R:  7E FF 06 41 00 00 00 FE BA EF -> 41 : Ack OK
Cback status: STS_ACK_OK, 0x0
R:  7E FF 06 42 00 02 00 FE B7 EF -> 42 : Status 0x200
Cback status: STS_STATUS, 0x200
R:  7E FF 06 41 00 00 00 FE BA EF -> 41 : Ack OK
Cback status: STS_ACK_OK, 0x0

Turning the Debugger off  -> gives me INCORRECT
initializing...

>Callback ON
>Synchronous ON
CW Speed Cal= 1882
CCW Speed Cal= 300
Cback status: STS_INIT, 0x2
Cback status: STS_ERR_FILE, 0x4
Cback status: STS_STATUS, 0x200
Starting...
Cback status: STS_ACK_OK, 0x0

Adding a delay of about 20mse to the debug off mode to both MD_YX5300::sendRqst and  MD_YX5300::processResponse 

#if LIBDEBUG
  //uint16_t td=millis();
  dumpMessage(_bufRx, _bufIdx, "R");
  //Serial.print(" RTime ");Serial.println (millis()-td);
#else 
   delay(20);
#endif

gives:

initializing...

>Callback ON
>Synchronous ON
CW Speed Cal= 1821
CCW Speed Cal= 300
Cback status: STS_INIT, 0x2
Cback status: STS_ACK_OK, 0x0
Cback status: STS_VOLUME, 0x19
Starting...
Cback status: STS_ACK_OK, 0x0
Cback status: STS_STATUS, 0x200
Cback status: STS_ACK_OK, 0x0

Am I doing something incorrect?

**Comment by MajicDesigns** [comment]
Have you tried to disable the calls to the Motor control stuff? It could be interfering with the serial interface and the extra timing you introduced somehow makes it work.

**Comment by ldalep** [comment]
I have put the player commands  outside the loop and in different places with the same results - That would be a far stretch because that is pure digital without any interrupts

**Comment by MajicDesigns** [comment]
OK, but as the code is not there I can't tell what it does or does not do, nor how you have arranged the power supply for the motors or what level of experience you have in debugging.

Back to the original question - have you actually tried NOT running the motor control code at all?

**Comment by ldalep** [comment]
Sorry about that -  So I did one better…. I used your MD_YX5300_Test and added the following:

void setup()
{
  Serial.begin(57600);
  mp3.begin();
  help();
  setCallbackMode(bUseCallback);
  setSynchMode(bUseSynch);
  
  mp3.volume(12);
  mp3.queryVolume();
  mp3.queryStatus();

  while (mp3.check());
}

and changed the following

#define ARDUINO_RX 11  // connect to TX of MP3 Player module
#define ARDUINO_TX 12  // connect to RX of MP3 Player module
bool bUseSynch = true;   // use synchronous? 

This if on a Arduino Pro Mini


I got the same results as I did with my program - without the delays it is corrupted.

**Comment by MajicDesigns** [comment]
Great. I can replicate that and check what's going on.

**Comment by ldalep** [comment]
Hi 

any luck on reproducing my issue

Dale

**Comment by MajicDesigns** [comment]
Won't get a chance to try until the week-end at the earliest.

**Comment by MajicDesigns** [comment]
If you are using synchronous mode, then your code needs to behave synchronously. The correct code construct is
    mp3.volume(12);
    while (!mp3.check());
    mp3.queryVolume();
    while (!mp3.check());
    mp3.queryStatus();
    while (!mp3.check());

otherwise you are sending 3 serial messages and the timeout processing gets screwed up, causing the additional response message.

**Comment by ldalep** [comment]
Thank you - I tried it that way as well and still had the issue

**Comment by ldalep** [comment]
Sorry - to be specific using your construct still yields the status time out - on the last query

**Comment by MajicDesigns** [comment]
On my system the timeout is intermittent. The device documentation says that
"4 , chip internal to the processing of the serial port is 10MS processing once, so sequential instructions must be sent at intervals 20MS the delay. Otherwise, the previous instruction will be overwritten without execution."
Overwrite without execution would imply a timeout at the library end. I will release a new version 1.1.0 of the library that adds a 20ms delay() delay after sending the message so as not to overload the device. That version works all the time on my system.

**Comment by ldalep** [comment]
Thanks - I will leave the 20msec delay in the code - I appreciate you looking into it.   I realize that you are busy but I would like to ask you a question about the use of softserial - this is done in the check() - I have an application for an art project which involves turning on and off the slave processor which is running the MP3 player - I am having difficulty with I2C bus locking up the master when the slave is turned off(power saving) .  The question is could I try using another soft serial port  instead of the i2c and switch back and for with “listen” commands or would I run the risk of missing important call back communications such as errors or end of play?

**Comment by MajicDesigns** [comment]
`Wow, that is complicated and I am not sure I follow what you are trying to do. Have you considered using the Arduino Forum to explain what you want to do and see if the collective brain can help?

**Comment by ldalep** [comment]
Thank you - I will do!
