### ISSUE TITLE
How to Check if Track is Playing

### ISSUE THREAD

**Issue by Good-man** [MajicDesigns/MD_YX5300#4]
In my code I want to start a track and continue doing other things in loop() until the track is finished.  Similar to the Busy check on DFPlayer.  Is there a way to do this with the YX5300 and your library?

**Comment by MajicDesigns** [comment]
The device sends a status message when the track is finished playing.The returned status values are listed in the library documentation.

**Comment by Good-man** [comment]
So there is no way to query for it?  I must be missing something.   I will read the comments in the header file.

**Comment by MajicDesigns** [comment]
html help file is in your docs folder or online from the readme.md on github. Look for the cdData structure.

**Comment by Good-man** [comment]
I tried your sample.  I get the same result whether a track is playing or not.  I am really disappointed in this library and your help.

**Comment by MajicDesigns** [comment]
Thanks for the feedback. I hope you find something and/or someone that suits you better.
