### ISSUE TITLE
Example for basic usage

### ISSUE THREAD

**Issue by mneuschaefer** [MajicDesigns/MD_YX5300#5]
Can you add an additional example for basic use of the library?

The example provided only works when you enter characters via serial. For most beginner projects however, it would be much clearer if there would be a basic example how to query folder files or play a random mp3 without any serial port input.

**Comment by MajicDesigns** [comment]
The example you quote It is meant as test code for the library and is essentially code fragments in a case statement. It illustrates how to handle responses (they all work the same way) that is also explained in the library reference documentation in the docs folder or from the link in the library repository home page.

**Comment by mneuschaefer** [comment]
thank you for the library and the extensive documentation, I find it currently difficult to use it for a kids mp3 player project as my understanding of cpp variables is still not that advanced. for example

  ```
int testvalue = mp3.queryFolderFiles(2);
  Serial.println(testvalue);
```

( in the main loop of the [example code](https://github.com/MajicDesigns/MD_YX5300/tree/master/examples/MD_YX5300_Test) provided) does not print the correct amount of files (it prints "0", but there are 10 files). Playing files with 

`mp3.playSpecific(02,02);` (pasted in the main loop) works so far, but not asynchronously.

I am sure these problems could be avoided with a better understanding of cpp - currently I find it difficult to even make sense of the information provided in the documentation (e.g. for "[getStatus()](https://majicdesigns.github.io/MD_YX5300/class_m_d___y_x5300.html#a0eca7a4949bc8ae414634aa8d529c0fa)":  "The status code is one of the status_t enumerated types". Despite the documentation I encounter even more problems than with sending serial commands directly (with code adapted from [here](https://github.com/cefaloide/ArduinoSerialMP3Player/blob/master/ArduinoSerialMP3Player/ArduinoSerialMP3Player.ino)). 

With other arduino libraries it is usually enough to just adapt the examples, unfortunately this is not the case here - it will take some time to get more proficient in understanding the language. Understanding the documentation of this library might need some practice as well. An example how to correctly pass query results to int variables or play files with asynchronous code execution would be really helpful to understand the code and to be able to adapt it.

**Comment by MajicDesigns** [comment]
Here's code for a simple mp3 player. You should use the latest version of the library as I added a function to provide the maximum volume:
`
// Simple MP3 player using the MD_YX5300 library.
//
// MP3 player has the following functions:
// - Start/pause track playback with single switch (momentary on type)
// - Play next track with single switch (momentary on type)
// - Volume control using potentiometer
// - Run state shown using LED indicator
//
// Implemented using synchronous calls and kept as simple as possible.
// All tracks need to be placed in folder PLAY_FOLDER (defined below)
//
// Library dependencies:
// MD_UISwitch can be found at https://github.com/MajicDesigns/MD_UISwitch
//

#include <MD_YX5300.h>
#include <MD_UISwitch.h>

// Connections for serial interface to the YX5300 module
const uint8_t ARDUINO_RX = 5;  // connect to TX of MP3 Player module
const uint8_t ARDUINO_TX = 6;  // connect to RX of MP3 Player module

const uint8_t SW_PLAY_PAUSE = 7; // play/pause toggle digital pin, active low (PULLUP)
const uint8_t SW_PLAY_NEXT = 8;  // play next track digital pin, active low (PULLUP)
const uint8_t PIN_LED = 9;       // LED to show status
const uint8_t POT_VOLUME = A0;   // volume control pot analog pin

const uint8_t PLAY_FOLDER = 1;   // tracks are all placed in this folder


#define DEBUG 0 // enable/disable debug output

#ifdef DEBUG
#define PRINT(s,v)    { Serial.print(F(s)); Serial.print(v); }
#define PRINTX(s,v)   { Serial.print(F(s)); Serial.print(v, HEX); }
#define PRINTS(s)     { Serial.print(F(s)); }
#else
#define PRINT(s,v)
#define PRINTX(s,v)
#define PRINTS(s)
#endif


// Define global variables
MD_YX5300 mp3(ARDUINO_RX, ARDUINO_TX);
MD_UISwitch_Digital swPause(SW_PLAY_PAUSE);
MD_UISwitch_Digital swNext(SW_PLAY_NEXT);

bool playerPause = true;  // true if player is currently paused


void processVolume(bool bForce = false)
// read the volume pot and set the volume if it has changed
{
  static uint8_t vol;   // current audio volume
  uint16_t pot = analogRead(POT_VOLUME);
  uint8_t newVolume = map(analogRead(POT_VOLUME), 0, 1023, 0, mp3.volumeMax());
  
  if (newVolume != vol || bForce)
  {
    PRINT("\nSetting volume ", newVolume);
    vol = newVolume;
    bool b = mp3.volume(vol);
    PRINT(" result ", b);
  }
}

void processPause(bool bForce = false)
// read the pause switch and act if it has been pressed
{
  MD_UISwitch::keyResult_t k = swPause.read();

  if (k == MD_UISwitch::KEY_PRESS || bForce)
  {
    bool b;

    if (!bForce) playerPause = !playerPause;
    PRINT("\nSwitching to ", playerPause ? F("PAUSE") : F("PLAY"));
    if (playerPause) b = mp3.playPause(); else b = mp3.playStart();
    PRINT(" result ", b);
  }
}

void processNext(bool bForce = false)
// read the next switch and act if it has been pressed
{
  MD_UISwitch::keyResult_t k = swNext.read();

  if (playerPause) return;    // this command makes no sense if paused

  if (k == MD_UISwitch::KEY_PRESS || bForce)
  {
    bool b;

    PRINTS("\nPlaying next");
    b = mp3.playNext();
    PRINT(" result ", b);
  }
}

void setStatusLED(void)
// set the status led - on for running, off for paused
{
  if (playerPause)
    digitalWrite(PIN_LED, LOW);
  else
    digitalWrite(PIN_LED, HIGH);
}

void setup()
{
#if DEBUG
  Serial.begin(57600);
#endif
  PRINTS("\n[MD_YX5300 Simple Player]");

  // set the hardware pins
  pinMode(PIN_LED, OUTPUT);
  pinMode(POT_VOLUME, INPUT);

  // initialize global libraries
  mp3.begin();
  mp3.setSynchronous(true);
  mp3.playFolderRepeat(PLAY_FOLDER);
  processVolume(true);    // force these to set up the hardware
  processPause(true);

  // Set up the switches modes - only simple switching
  swPause.begin();
  swPause.enableDoublePress(false);
  swPause.enableRepeat(false);
  swPause.enableLongPress(false);
  swNext.begin();
  swNext.enableDoublePress(false);
  swNext.enableRepeat(false);
  swNext.enableLongPress(false);
}

void loop()
{
  mp3.check();        // run the mp3 receiver
  processVolume();    // set the volume if required
  processPause();     // process the Pause switch
  processNext();      // provess the Next switch
  setStatusLED();     // set the status LED to current status
}
`

**Comment by mneuschaefer** [comment]
vielen Dank! Die Beispiele sind wirklich hilfreich, nun verstehe ich den
Ablauf viel besser.

Nun geht es wieder voran mit dem Hörbert-Klon, wenn es fertig ist stelle ich das auf github - eine populäre Anleitung <https://www.mikrocontroller.net/topic/439485> läuft ständig in Probleme
weil die DFPlayer-Klone leider oft nicht so funktionieren wie beschrieben, mit dem MD_YX5300 klappt das nun zuverlässig.

viele Grüße,
Markus

Translation:
-----
Thanks a lot! The examples are really helpful, now I understand that process much better.

Now it's back to the Hörbert clone, when it's done I put that on github - a popular guide <https://www.mikrocontroller.net/topic/439485> is always in trouble unfortunately the DFPlayer clones often do not work as described, with the MD_YX5300 this works reliably now.
 -----
