### ISSUE TITLE
Compilation error on ESP32

### ISSUE THREAD

**Issue by thijstriemstra** [MajicDesigns/MD_YX5300#8]
I'm building this for ESP32 using platformio.ini:

```ini
[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 9600

lib_deps =
  MD_YX5300
```

Results in this error:

```
.pio/libdeps/lolin32/MD_YX5300_ID5592/src/MD_YX5300.h:12:28: fatal error: SoftwareSerial.h: No such file or directory
```

So I add `SoftwareSerial` to `lib_deps` in `platformio.ini` but the error doesn't go away. So I found a esp32 version of SoftwareSerial: https://github.com/plerup/espsoftwareserial

After adding `EspSoftwareSerial` to `lib_deps` in `platformio.ini` it compiles, but now throws many errors like this:

```
.pio/libdeps/lolin32/MD_YX5300_ID5592/src/MD_YX5300.h:1125:12: error: 'MD_YX5300::_timeout' will be initialized after [-Werror=reorder]
   uint32_t _timeout;  ///< timeout for return serial message
            ^
.pio/libdeps/lolin32/MD_YX5300_ID5592/src/MD_YX5300.h:1124:8: error:   'bool MD_YX5300::_synch' [-Werror=reorder]
   bool _synch;        ///< synchronous (wait for response) if true
        ^
.pio/libdeps/lolin32/MD_YX5300_ID5592/src/MD_YX5300.h:461:3: error:   when initialized here [-Werror=reorder]
   MD_YX5300(uint8_t pinRx, uint8_t pinTx) : 
```

To fix that I added this to `platformio.ini`:

```ini
; Used for YX5300 audio player, see https://github.com/MajicDesigns/MD_YX5300/issues/8
build_unflags = -Werror=reorder
```

And it now compiles. But is this the correct way to do it @MajicDesigns?

**Comment by MajicDesigns** [comment]
You should be ok with these settings.

ESP32 compilers by default turn on many warning/errors that are irrelevant. I really don't understand why they did this. 

The fact that a variable is initialised before or after another ([-Werror=reorder]) has no bearing on the way the code behaves if there are no dependencies between them. That is what those 'errors' that you turned off were telling you.

If it worries you just change the order of the variables
'   _timeout(1000), _synch(true), _cbStatus(nullptr)
to be
'  _cbStatus(nullptr),  _synch(true), _timeout(1000)

**Comment by thijstriemstra** [comment]
> You should be ok with these settings.

I'm afraid it'll shadow other errors so I'd rather turn it off. It means this library doesn't work out of the box with ESP32 without consulting this ticket though..

> If it worries you just change the order of the variables

I think I'll do that. I have it working now, but there's an unbearable hum/high pitched noise on the line. I'm using a PAM8610 amp and when I plug an ipod the signal is as clean as it can be. any idea...?

**Comment by thijstriemstra** [comment]
Opened a pull request: #9 

ESP32 now works.

If you're using platformio, this patched version can be installed using `platformio.ini`:

```ini
lib_deps =
  EspSoftwareSerial
  MD_YX5300=https://github.com/thijstriemstra/MD_YX5300/archive/patch-1.zip
```

> there's an unbearable hum/high pitched noise on the line. I'm using a PAM8610 amp and when I plug an ipod the signal is as clean as it can be. any idea...?

See https://github.com/Edzelf/ESP32-Radio/issues/66 for various fixes.
